wandb_version: 1

data.batch_size:
  value: 32
model.backbone:
  value: mobilenet_v3_small
model.dropout:
  value: 0.2
train.label_smoothing:
  value: 0.1
train.lr_phase1:
  value: 0.001
train.lr_phase2:
  value: 0.0003
