name: DL
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch
      - torchvision
      - wandb
      - pyyaml
      - scikit-learn
      - matplotlib
      - seaborn
      - ipykernel
      - fastapi
      - uvicorn[standard]
      - streamlit
      - requests
      - pillow
      - python-multipart